[package]
name = "garlic"
version = "0.2.3"
edition = "2024"
repository = "https://github.com/gubsey/garlic"
license = "MIT"
description = "A collection of random side projects"
documentation = "https://docs.rs/garlic"

[dependencies]
